# compose/deployment/Dockerfile.db
FROM postgres:16
EXPOSE 5432


# Add maintenance scripts (if any)
# COPY ./compose/deployment/postgres/maintenance /usr/local/bin/maintenance
# RUN chmod +x /usr/local/bin/maintenance/* \
#    && mv /usr/local/bin/maintenance/* /usr/local/bin \
#    && rmdir /usr/local/bin/maintenance